config/routes.rb
Rails.application.routes.draw do
  root "fiesta#index"
  
  # DEVISE USER RAILS 7 STUFF #
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users, :controllers => {registrations: "registrations"}

  # PROFILE PAGE #
  get '/fiesta/perfil', to: 'fiesta#perfil'
  # SHOW ATTENDING FIESTAS IN PROFILE PAGE #
  get '/users/:id/attended_events', to: "users#show_attended_fiesta", as: "show_attended_fiesta"

  # PROXIMAS AND PASADAS PAGES #
  get '/fiesta/pasadas', to: 'fiesta#fiesta_pasadas'
  get '/fiesta/proximas', to: 'fiesta#fiesta_proximas'

  # FROM SCAFFOLDING FIESTA #
  resources :fiesta

  # NOT ATTENDING FIESTAS #
  delete 'fiesta/:id/users/:user_id/', to: "attending_fiesta#destroy", as: "destroy_attending_fiestum"
  # ATTENDING FIESTAS #
  post 'fiesta/:id/users/:user_id/', to: "attending_fiesta#create", as: "create_attending_fiestum"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attending_fiestum.rb
class AttendingFiestum < ApplicationRecord
  belongs_to :user
  belongs_to :fiestum
end

app/models/fiestum.rb
class Fiestum < ApplicationRecord
  validates :nombre, presence: true
  validates :descripcion, presence: true
  validates :lugar, presence: true
  validates :fetcha, presence: true
  validates :imagen, attached: true, size: { less_than: 500.kilobytes , message: 'es demasiado grande' }

  belongs_to :creator, class_name: 'User'

  has_many :attending_fiesta
  has_many :attendees, through: :attending_fiesta, source: :user
  has_one_attached :imagen

  scope :proximas, -> {where('fetcha >= ?', Time.now)}
  scope :pasadas,   -> {where('fetcha < ?', Time.now)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_fiesta, foreign_key: "creator_id", class_name: "Fiestum", dependent: :destroy

  has_many :attending_fiesta, dependent: :destroy
  has_many :attended_fiesta, through: :attending_fiesta, source: :fiestum, foreign_key: "attendee_id"

  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attending_fiesta_controller.rb
class AttendingFiestaController < ApplicationController
  def new
    @fiestum = Fiestum.find(params[:id])
  end

  # Join a party
  def create
    @fiestum = Fiestum.find(params[:id])
    @fiestum.attendees << current_user
    flash[:notice] = "Se registró para la fiesta. Genial!"
    redirect_to request.referer #, anchor:  "fiestum_#{@fiestum.id}"
  end

  def destroy
    @fiestum = Fiestum.find(params[:id])
    @fiestum.attendees.delete(current_user)
    flash[:alert] = "¿Por qué no quieres ir a la fiesta? No registrado."
    #redirect_back(fallback_location: root_path)   #<--- this aint working
    redirect_to root_path #, anchor: "fiestum_#{@fiestum.id}"
  end
end

app/controllers/fiesta_controller.rb
class FiestaController < ApplicationController
  before_action :set_fiestum, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :fiesta_pasadas, :fiesta_proximas]

  # GET /fiesta or /fiesta.json
  def index
    @fiesta = Fiestum.all
  end

  # GET /fiesta/1 or /fiesta/1.json
  def show
  end

  # GET /fiesta/new
  def new
    @fiestum = current_user.created_fiesta.build 
  end

  # GET /fiesta/perfil
  def perfil
    @fiesta = current_user.created_fiesta.all
    @attended_fiesta = current_user.attended_fiesta #<---- to view attended events on profile page
  end

  # GET /fiesta/pasadas
  def fiesta_pasadas
    @fiesta = Fiestum.all
  end

  # GET /fiesta/proximas
  def fiesta_proximas
    @fiesta = Fiestum.all
  end

  # GET /fiesta/1/edit
  def edit
    if current_user.id == @fiestum.creator_id
      current_user.created_fiesta.find(params[:id])
    else
      redirect_to root_path, :alert => "Area prohibido" 
    end
  end

  # POST /fiesta or /fiesta.json
  def create
    @fiestum = current_user.created_fiesta.build(fiestum_params)

    respond_to do |format|
      if @fiestum.save
        format.html { redirect_to root_path, notice: "Creó una nueva fiesta." }
        format.json { render :show, status: :created, location: @fiestum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fiestum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fiesta/1 or /fiesta/1.json
  def update
    respond_to do |format|
      if @fiestum.update(fiestum_params)
        format.html { redirect_to fiestum_url(@fiestum), notice: "Fiesta se actualiza" }
        format.json { render :show, status: :ok, location: @fiestum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fiestum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiesta/1 or /fiesta/1.json
  def destroy
    if current_user.id == @fiestum.creator_id
      @fiestum.destroy
      respond_to do |format|
        format.html { redirect_to fiesta_url, notice: "Se cancela la fiesta" }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, :alert => "Area prohibido" 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fiestum
      @fiestum = Fiestum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fiestum_params
      params.require(:fiestum).permit(:nombre, :descripcion, :fetcha, :lugar, :imagen)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end 
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
  def randomized_background_image
    #images = ["images/home_banner/0.jpg", 
    #          "images/home_banner/1.jpg", 
    #          "images/home_banner/2.jpg",
    #          "images/home_banner/3.jpg",
    #          "images/home_banner/4.jpg"
    #        ]
    images = ["bg-randomhead0", 
              "bg-randomhead1", 
              "bg-randomhead2",
              "bg-randomhead3",
              "bg-randomhead4"
            ]
            
    images[rand(images.size)]
  end
end

app/helpers/attending_fiesta_helper.rb
module AttendingFiestaHelper
end

app/helpers/fiesta_helper.rb
module FiestaHelper
end

app/views/fiesta/_bubble.html.erb
<div id="<%= dom_id fiestum %>" class="flex flex-col justify-start bg-white drop-shadow-md rounded-xl p-0 mx-2 mb-5 w-72"> 
  <!--Picture-->
  <div class="text-center h-48 w-72 ">
    <%= link_to fiestum do %>
      <%= image_tag fiestum.imagen, class: "h-48 object-cover w-full rounded-t-xl" %>
    <% end %>
  </div>

  <!--Date-->
  <div class="px-3">
    <strong class="block font-medium mb-1">
      <%= link_to fiestum, class: "text-xs hover:text-gray-600" do %>
        <%#= fiestum.fetcha.strftime("%^a, %^b %-d, %Y") %>
        <%=  I18n.localize(fiestum.fetcha, :format => '%^a, %^b %-d, %Y') %>
      <% end %>
    </strong>
  </div>

  <!--Name-->
  <div class="px-3">
    <strong class="block font-medium mb-1 truncate">
      <%= link_to fiestum.nombre, fiestum, class: "hover:text-gray-600" %>
    </strong>
  </div>

  <!--Location.-->
  <div class="px-3 truncate">
    <%= link_to fiestum.lugar, fiestum, class: "hover:text-gray-600 " %>
  </div>

  <!--Created by-->
  <div class="px-3 italic text-xs mb-3 truncate">
    <%= link_to fiestum, class: "hover:text-gray-600" do %>
      Credado por @<%= fiestum.creator.username %>
    <% end %>
  </div>

  <!--buttons-->  
  <% if user_signed_in? %>
    <div class="flex flex-row justify-between items-start">
      <% if current_user && fiestum.creator != current_user && !fiestum.attendees.include?(current_user) %>
        <%= link_to create_attending_fiestum_path(:user_id => current_user.id, :id => fiestum.id), data: { turbo_method: :post }, class: "px-3 bg-slate-100 w-5/6 m-3 mr-1 mt-0 text-center rounded-md hover:bg-slate-200 " do %>
          ★ Interestante
        <% end %>
      <% elsif fiestum.creator == current_user %>
        <%= link_to fiestum, class: "px-3 bg-slate-300 w-5/6 m-3 mr-1 mt-0 text-center rounded-md hover:bg-slate-400 " do %>
          ✓ Creaste la fiesta
        <% end %>      
      <% else %>
        <%= link_to destroy_attending_fiestum_path(:user_id => current_user.id, :id => fiestum.id), data: { turbo_method: :delete }, class: "px-3 bg-slate-300 w-5/6 m-3 mt-0 mr-1  text-center rounded-md hover:bg-slate-400 " do %>
          ✓ Vamos a la fiesta
        <% end %>
      <% end %>
      
      <%= link_to fiestum, class: "px-3 bg-slate-100 w-1/6 m-3 mt-0 text-center rounded-md hover:bg-slate-200 " do %>
          ?
      <% end %>
    </div>
  <% end %>
</div>

app/views/fiesta/_homebanner.html.erb
<header class="w-full h-96 bg-head <%= randomized_background_image %> bg-cover bg-center flex justify-center items-center">
    <div class="flex flex-col justify-center items-center drop-shadow-2xl">
        <h1 class=" text-center text-5xl text-amber-200 font-bold">El Lugar<br>
        <span class="text-amber-100 text-4xl">Para encontrando las fiestas</span>
        </h1>
        <p class="my-5 text-center text-xl text-white">En su área y región</p>
        <%= link_to 'Nueva Fiesta', new_fiestum_path, class: "text-center block p-3 px-6 text-slate-900 bg-amber-100 rounded-full hover:bg-amber-200" %>
        
    </div>
</header>

      <%#= image_tag "fiestas/#{rand(12)}", class: "object-cover min-w-full md:rounded-t-2xl" %>

app/views/fiesta/_navbar.html.erb
<!-- Navbar -->
<nav class="relative p-6 bg-gray-700 text-white">
  <!--Notice-->
  <div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 w-full text-center bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="py-2 px-3 w-full text-center bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>
  </div>
  <!--Flex container-->
  <div class="flex flex-col md:flex-row items-center justify-between">
    <!--Logo-->
    <div class="pt-2 flex flex-row items-center gap-5 mr-2">
      <!--Image-->
      <div class="">
        <%= image_tag "logo_hat.png", class: "max-h-40 md:max-h-20" %>
      </div>
      <!--text-->
      <h1 class="font-curs text-5xl hover:text-slate-500">
        <%= link_to 'Fiesta Encontrando', root_path %>
      </h1>
    </div>

    <!--Menu Items-->
    <div class="flex flex-col md:flex-row md:items-center md:space-x-6 gap-3 mt-3">
      <%= link_to 'Fiestas Pasadas', fiesta_pasadas_path, method: :get, 'data-turbo': false, class: "hidden hover:text-slate-500 md:block" %>
      <%= link_to 'Fiestas Próximas', fiesta_proximas_path, method: :get, 'data-turbo': false, class: "hidden hover:text-slate-500 md:block" %>
      <!--Buttons-->
      <% if user_signed_in? %>
        <%= button_to 'Desconecta', destroy_user_session_path, method: :delete, class: "text-center block p-3 px-6 text-slate-900 bg-slate-300 rounded-full hover:bg-slate-200" %>
        <%= link_to 'Perfil', fiesta_perfil_path, method: :get, 'data-turbo': false, class: "text-center block p-3 px-6 text-white bg-slate-900 rounded-full hover:bg-slate-800" %>
      <% else %>
        <%= link_to 'Inscribe', new_user_registration_path, class: "text-center block p-3 px-6 text-slate-900 bg-slate-300 rounded-full hover:bg-slate-200" %>
        <%= link_to 'Inicia', new_user_session_path, class: "text-center block p-3 px-6 text-white bg-slate-900 rounded-full hover:bg-slate-800" %>
      <% end %>
    </div>

  </div>
</nav>    

app/views/fiesta/_pasadas.html.erb
<!--Fiestas Pasadas-->
<div class="bg-white px-2 md:px-10 md:pb-10 md:pt-5 ">
  <!--Headline and view more-->
  <div class="flex flex-row justify-between items-center py-3">
    <!--Headline-->
    <div class="font-bold text-2xl">
      Fiestas Pasadas
    </div>
        <!--View More-->
    <%= link_to fiesta_pasadas_path  do %>        
    <div class="text-slate-500 hover:bg-slate-100 rounded-xl p-2 hidden md:block">
      Ver más
    </div>
    <% end %>
  </div>
  <!--Actual feed content-->
  <div class="flex flex-row justify-center">
    <div class="flex flex-col items-center pb-10 md:max-w-fit md:grid md:grid-cols-2 lg:grid-cols-3 md:justify-center md:place-items-center md:gap-3" >
      <% @fiesta.pasadas.order(:fetcha).last(6).reverse_each do | fiestum | %>
        <%= render "bubble", fiestum: fiestum  %>
      <% end %>

      <!--View more button-->
      <div class="flex flex-col items-center justify-center bg-white drop-shadow-md rounded-xl w-72 h-32 p-0 mx-2 mb-5 md:hidden">
        <%= link_to fiesta_pasadas_path  do %>        
          <div class="flex flex-row justify-center text-slate-500 hover:bg-slate-100 rounded-xl p-2 w-30">
            Ver más
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/fiesta/_proximas.html.erb
<!--Fiestas proximas section-->
<div class="bg-white px-2 md:px-10 md:pb-10 md:pt-5 ">
  <!--Headline and view more-->
  <div class="flex flex-row justify-between items-center py-3">
    <!--Headline-->
    <div class="font-bold text-2xl">
      Fiestas Proximas
    </div>
    <!--View More-->
    <%= link_to fiesta_proximas_path  do %>        
      <div class="text-slate-500 hover:bg-slate-100 rounded-xl p-2">
        Ver más
      </div>
    <% end %>
  </div>
  <!--Actual feed content-->
  <div class="flex flex-row justify-center">
    <div class="flex flex-row overflow-x-scroll pb-10 md:max-w-fit md:grid md:grid-cols-2 lg:grid-cols-3 md:justify-center md:place-items-center md:gap-3 md:overflow-y-auto" >
      <% @fiesta.proximas.order(fetcha: :desc).last(6).reverse_each do | fiestum | %>
        <%= render "bubble", fiestum: fiestum %>
      <% end %>
    </div>
  </div>
</div>

app/views/fiesta/edit.html.erb
<%= render 'navbar' %>

<%= image_tag @fiestum.imagen, class: "object-cover min-w-full md:hidden"%>
<div class="mx-auto md:w-1/2 w-full p-5">
  <%= image_tag @fiestum.imagen, class: "object-cover min-w-full rounded-2xl hidden md:block"%>
  <div class="flex flex-row justify-between items-center py-3">
    <!--Headline-->
    <div class="font-bold text-2xl">
      Edita Fiesta
    </div>
    <%= link_to root_path do %>
      <div class="text-slate-500 hover:bg-slate-100 rounded-xl p-2">
        ↩ Vuelve Atrás
      </div>
    <% end %>
    
  </div>

  <%= render "form", fiestum: @fiestum %>

  <!--Cancel button-->
  <%= button_to 'Cancela la fiesta', fiestum_path(@fiestum), method: :delete, class: "mt-2 w-full text-center rounded-lg py-3 px-5 bg-gray-100 hover:bg-red-300 inline-block font-medium" %>
  <!--Back button-->
  <div class="inline">
    <%= link_to "Vuelve Atrás", 'javascript:history.back()',  class: "mt-2 w-full text-center rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium" %>
  </div>
</div>

app/views/fiesta/fiesta_pasadas.html.erb
<%= render 'navbar' %>
<%= render 'homebanner' %>
<h1 class="my-4 text-2xl font-bold text-center text-gray-700">
  Todos Fiestas Pasadas
</h1>
<!--forked from Fiestas Pasadas-->
<div class="bg-white px-2 md:px-10 md:pb-10 md:pt-5 ">
  <!--Actual feed content-->
  <div class="flex flex-row justify-center">
    <div class="flex flex-col items-center pb-10 md:max-w-fit md:grid md:grid-cols-2 lg:grid-cols-3 md:justify-center md:place-items-center md:gap-3" >
      <% @fiesta.pasadas.order(:fetcha).reverse_each do | fiestum | %>
        <%= render "bubble", fiestum: fiestum %>  
      <% end %>
    </div>
  </div>

</div>

app/views/fiesta/fiesta_proximas.html.erb
<%= render 'navbar' %>
<%= render 'homebanner' %>
<h1 class="my-4 text-2xl font-bold text-center text-gray-700">
  Todos Fiestas Proximas
</h1>
<!--forked from Fiestas Pasadas-->
<div class="bg-white px-2 md:px-10 md:pb-10 md:pt-5 ">
  <!--Actual feed content-->
  <div class="flex flex-row justify-center">
    <div class="flex flex-col items-center pb-10 md:max-w-fit md:grid md:grid-cols-2 lg:grid-cols-3 md:justify-center md:place-items-center md:gap-3" >
      <% @fiesta.proximas.order(:fetcha).reverse_each do | fiestum | %>
        <%= render "bubble", fiestum: fiestum %>  
      <% end %>
    </div>
  </div>

</div>

app/views/fiesta/index.html.erb
<%= render 'navbar' %>
<%= render 'homebanner' %>
<%= render 'content' %>

app/views/fiesta/new.html.erb
<%= render 'navbar' %>

<div class="mx-auto md:w-1/2 w-full p-5">
  <div class="flex flex-row justify-between items-center py-3">
    <!--Headline-->
    <div class="font-bold text-2xl">
      Nueva Fiesta
    </div>
    <%= link_to root_path do %>
      <div class="text-slate-500 hover:bg-slate-100 rounded-xl p-2">
        ↩ Vuelve Atrás
      </div>
    <% end %>
    
  </div>

  <%= render "form", fiestum: @fiestum %>

  <!--Back button-->
  <div class="inline">
    <%= link_to "Vuelve Atrás", 'javascript:history.back()',  class: "mt-2 w-full text-center rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium" %>
  </div>
  
</div>

app/views/fiesta/pagina_pasadas.html.erb
hello world

app/views/fiesta/pagina_proximas.html.erb
Hello Jupiter

app/views/fiesta/perfil.html.erb
<%= render 'navbar' %>

<main class="container mx-auto px-5 flex">
  <div class="w-full">
    <% if notice.present? %>
      <p class="mt-4 bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" id="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="mt-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" id="alert"><%= alert %></p>
    <% end %>
    
    <!--Attending events -->
    <h1 class="my-4 text-2xl font-bold text-center text-gray-700">
      Próximas fiestas a las que va
    </h1>
    <div id="" class="">
      <%= render 'fiesta/perfil/fiestas_proximas' %>
    </div>

    <!--Attending events -->
    <h1 class="my-4 text-2xl font-bold text-center text-gray-700">
      Las fiestas que fue
    </h1>
    <div id="" class="">
      <%= render 'fiesta/perfil/fiestas_pasadas' %>
    </div>

    <!--mis mifiestas feed (the parties I created) -->
    <h1 class="my-4 text-2xl font-bold text-center text-gray-700">
      Las fiestas que creó
    </h1>
    <div id="" class="">
      <%= render 'fiesta/perfil/creo' %>
    </div>

  </div>
</main>

app/views/fiesta/show.html.erb
<div class="flex flex-col items-center">
  <!-- Navbar mobile only-->
  <div class="md:hidden">
    <nav class="relative p-6 bg-gray-700 text-white w-full">
      <!--Notice-->
      <div class="w-full">
      <% if notice.present? %>
        <p class="py-2 px-3 w-full text-center bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="py-2 px-3 w-full text-center bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
      <% end %>
      </div>
      <!--Flex container-->
      <div class="flex flex-col md:flex-row items-center justify-between">
        <!--Logo-->
        <div class="pt-2 flex flex-row items-center gap-5">
          <!--Image-->
          <div class="">
            <%= image_tag "logo_hat.png", class: "max-h-40 md:max-h-20" %>
          </div>
          <!--text-->
          <h1 class="font-curs text-5xl hover:text-slate-500">
            <%= link_to 'Fiesta Encontrando', root_path %>
          </h1>
        </div>
      </div>
    </nav>
  </div>
  <div class="hidden md:block md:w-full">
    <%= render 'navbar' %>
  </div>
  <!--Main container-->
  <div class="w-full md:w-1/2 md:my-5 pb-3 md:bg-white md:drop-shadow-xl md:rounded-2xl">
    <!--Image-->
    <div class="text-center">
      <%= image_tag @fiestum.imagen, class: "object-cover min-w-full md:rounded-t-2xl" %>
    </div>
    
    <!--date-->
    <div class="mt-2 px-5 text-xs font-medium">
      <%= @fiestum.fetcha.strftime("%^a, %^b %-d, %Y") %> at <%= @fiestum.fetcha.strftime("%l:%M %p") %>
    </div>
    
    <!--Name-->
    <div class="px-5">
      <strong class="block font-bold text-2xl truncate">
        <%= @fiestum.nombre %>
      </strong>
    </div>

    <!--Location.-->
    <div class="px-5 text-slate-700 truncate">
      <%= @fiestum.lugar %>
    </div>

    <!--Buttons-->
    <div class="flex flex-row justify-around text-sm">
      <!--star-->
      <% if user_signed_in? %>
        <% if current_user && @fiestum.creator != current_user && !@fiestum.attendees.include?(current_user) %>
          <div class="flex flex-col m-3">
            <%= link_to create_attending_fiestum_path(:user_id => current_user.id, :id => @fiestum.id), data: { turbo_method: :post }, class: "flex flex-col items-center text-center" do %>
              <div class="bg-slate-100 w-min px-3 py-1 rounded-full text-xl text-bold text-black hover:bg-slate-300 lg:rounded-lg lg:mb-2 lg:w-36">
                ★
              </div>
              Interestante
            <% end %>
          </div>
        <% elsif @fiestum.creator == current_user %>
          <div class="flex flex-col m-3">
            <%= link_to @fiestum, class: "flex flex-col items-center text-center" do %>
              <div class="bg-slate-300 w-min px-3 py-1 rounded-full text-xl text-bold text-black hover:bg-slate-400 lg:rounded-lg lg:mb-2 lg:w-36">
                ✓ 
              </div>
              Creaste la fiesta
            <% end %> 
          </div>
        <% else %>
          <div class="flex flex-col m-3">
            <%= link_to destroy_attending_fiestum_path(:user_id => current_user.id, :id => @fiestum.id), data: { turbo_method: :delete }, class: "flex flex-col items-center text-center" do %>
              <div class="bg-slate-300 w-min px-3 py-1 rounded-full text-xl text-bold text-black hover:bg-slate-400 lg:rounded-lg lg:mb-2 lg:w-36">
                ✓
              </div>
              Vamos a la fiesta
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="flex flex-col m-3">
          <%= link_to new_user_session_path, class: "flex flex-col items-center text-center" do %>
            <div class="bg-slate-100 w-min px-3 py-1 rounded-full text-xl text-bold text-black hover:bg-slate-300 lg:rounded-lg lg:mb-2 lg:w-36">
              ★
            </div>
            Inicia para <br>ir alas fiestas
          <% end %>
        </div>
      <% end %>
      <!--more info-->
      <div class="flex flex-col items-center text-center m-3">
        <div class="bg-slate-100 text-black w-min px-3 py-1 rounded-full text-center text-xl text-bold hover:bg-slate-300 lg:rounded-lg lg:mb-2 lg:w-36">
          ＋
        </div>
        Más información
      </div>
      <!--back-->
      <div class="flex flex-col m-3">
        <%= link_to root_path, class: "flex flex-col items-center text-center" do %>
          <div class="bg-slate-100 w-min px-3 py-1 rounded-full text-xl text-bold text-black hover:bg-slate-300 lg:rounded-lg lg:mb-2 lg:w-36">
            ↩
          </div>
          Vuelve Atrás
        <% end %>
      </div>
    </div>

    <!--What to expect-->
    <div class="px-5">
      <strong class="block font-bold text-lg">
        Que esperar
      </strong>
      <div class="text-ellipsis overflow-hidden"> 
        <%= @fiestum.descripcion %>
      </div>
    </div>

    <!--Meet the host-->
    <div class="px-5">
      <strong class="block font-bold text-lg">
        Conoce al creador de fiesta
      </strong>
      @<%= @fiestum.creator.username %> crea esta fiesta en <%= @fiestum.created_at.strftime("%b %-d, %Y") %>
    </div>

    <!--who's going-->
    <div class="px-5">
      <strong class="block font-bold text-lg">
        ¿Quien va?
      </strong>
      <% @fiestum.attendees.reverse_each do |attendee| %>
        @<%= attendee.username %> 
      <% end %>
    </div>

    <!--Bottom buttons-->
    <% if @fiestum.creator == current_user %>
      <div class="mt-6 mb-3 px-5">
      <%= link_to 'Edita su fiesta', edit_fiestum_path(@fiestum), class: "mt-2 w-full text-center rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium" %>
      </div>
    <% end %>
  </div>
</div>